FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy all project files into the container
COPY . /app

# Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt
RUN python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab')"

# Build arguments for environment variables
ARG OPENAI_API_KEY
ARG PINECONEDB_API_KEY
ARG SERVICE_TITAN_TENANT_ID
ARG SERVICE_TITAN_CLIENT_ID
ARG SERVICE_TITAN_CLIENT_SECRET
ARG SERVICE_TITAN_BASE_AUTH_URL
ARG SERVICE_TITAN_BASE_API_URL
ARG SERVICE_TITAN_APP_KEY
ARG SERVICE_TITAN_BOOKING_PROVIDER_ID
ARG SLACK_BOT_TOKEN
ARG SLACK_SIGNING_SECRET
ARG VONAGE_API_KEY
ARG VONAGE_API_SECRET
ARG VONAGE_FROM_NUMBER
ARG VONAGE_APPLICATION_ID
ARG NOTION_API_TOKEN
ARG NOTION_TEAM_CONTACT_PAGE_DATABASE_ID

# Pass the arguments to environment variables
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV PINECONEDB_API_KEY=$PINECONEDB_API_KEY
ENV SERVICE_TITAN_TENANT_ID=$SERVICE_TITAN_TENANT_ID
ENV SERVICE_TITAN_CLIENT_ID=$SERVICE_TITAN_CLIENT_ID
ENV SERVICE_TITAN_CLIENT_SECRET=$SERVICE_TITAN_CLIENT_SECRET
ENV SERVICE_TITAN_BASE_AUTH_URL=$SERVICE_TITAN_BASE_AUTH_URL
ENV SERVICE_TITAN_BASE_API_URL=$SERVICE_TITAN_BASE_API_URL
ENV SERVICE_TITAN_APP_KEY=$SERVICE_TITAN_APP_KEY
ENV SERVICE_TITAN_BOOKING_PROVIDER_ID=$SERVICE_TITAN_BOOKING_PROVIDER_ID
ENV SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
ENV SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET
ENV VONAGE_API_KEY=$VONAGE_API_KEY
ENV VONAGE_API_SECRET=$VONAGE_API_SECRET
ENV VONAGE_FROM_NUMBER=$VONAGE_FROM_NUMBER
ENV VONAGE_APPLICATION_ID=$VONAGE_APPLICATION_ID
ENV NOTION_API_TOKEN=$NOTION_API_TOKEN
ENV NOTION_TEAM_CONTACT_PAGE_DATABASE_ID=$NOTION_TEAM_CONTACT_PAGE_DATABASE_ID

# Add the current working directory to PYTHONPATH
ENV PYTHONPATH=/app/app

# Expose the default port for the application
EXPOSE 8080

# Echo environment variables to verify they are set
RUN echo "OPENAI_API_KEY=$OPENAI_API_KEY" && \
    echo "PINECONEDB_API_KEY=$PINECONEDB_API_KEY" && \
    echo "SERVICE_TITAN_TENANT_ID=$SERVICE_TITAN_TENANT_ID" && \
    echo "SERVICE_TITAN_CLIENT_ID=$SERVICE_TITAN_CLIENT_ID" && \
    echo "SERVICE_TITAN_CLIENT_SECRET=$SERVICE_TITAN_CLIENT_SECRET" && \
    echo "SERVICE_TITAN_BASE_AUTH_URL=$SERVICE_TITAN_BASE_AUTH_URL" && \
    echo "SERVICE_TITAN_BASE_API_URL=$SERVICE_TITAN_BASE_API_URL" && \
    echo "SERVICE_TITAN_APP_KEY=$SERVICE_TITAN_APP_KEY" && \
    echo "SERVICE_TITAN_BOOKING_PROVIDER_ID=$SERVICE_TITAN_BOOKING_PROVIDER_ID" && \
    echo "SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN" && \
    echo "SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET" && \
    echo "VONAGE_API_KEY=$VONAGE_API_KEY" && \
    echo "VONAGE_API_SECRET=$VONAGE_API_SECRET" && \
    echo "VONAGE_FROM_NUMBER=$VONAGE_FROM_NUMBER" && \
    echo "VONAGE_APPLICATION_ID=$VONAGE_APPLICATION_ID" && \
    echo "NOTION_API_TOKEN=$NOTION_API_TOKEN" && \
    echo "NOTION_TEAM_CONTACT_PAGE_DATABASE_ID=$NOTION_TEAM_CONTACT_PAGE_DATABASE_ID"
    


# Run the FastAPI application
CMD ["uvicorn", "main:project", "--host", "0.0.0.0", "--port", "8080"]
