name: Deploy to GCP

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/fastapi-app:$GITHUB_SHA
        run: |
          echo "Docker image to be built and pushed: $IMAGE"
          docker build \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg PINECONEDB_API_KEY=${{ secrets.PINECONEDB_API_KEY }} \
            -t $IMAGE .
          docker push $IMAGE

      - name: Debug Docker Image Variable
        env:
          IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/fastapi-app:$GITHUB_SHA
        run: echo "Deploying Docker image: $IMAGE"

      - name: Deploy to Cloud Run
        env:
          IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/fastapi-app:$GITHUB_SHA
        run: |
          echo "Deploying image to Cloud Run: $IMAGE"
          gcloud run deploy fastapi-service \
            --image $IMAGE \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
