name: Deploy to GCP

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Debug Authentication
        run: gcloud auth list

      - name: Test Docker Authentication
        run: docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/fastapi-app:$GITHUB_SHA"
          docker build \
            --build-arg MY_API_KEY=${{ secrets.MY_API_KEY }} \
            --build-arg MY_OTHER_KEY=${{ secrets.MY_OTHER_KEY }} \
            -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --image $IMAGE \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
